services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    restart: always
    ports:
      - ${WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress:/usr/src/wordpress
    depends_on:
      - db
    networks:
      - network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    restart: always
    ports:
      - ${FRONTEND_PORT}:3000
    depends_on:
      - wordpress
    networks:
      - network

volumes:
  wordpress:
  db:

networks:
  network:
    driver: bridge
